---
- name: Listen for events from AlertManager
  hosts: localhost

  sources:
    - name: listen for alerts
      ansible.eda.alertmanager:
        host: 0.0.0.0
        port: 5001
        data_alerts_path: alerts
        data_host_path: labels.instance
        data_path_separator: .

  rules:
    - name: condicao DEBUG
      condition: event.payload is defined
      action:
        debug:
          var: event.payload
