---
- name: Listen for events from AlertManager
  hosts: localhost

  sources:
    - name: listen for alerts
      ansible.eda.alertmanager:
        host: 0.0.0.0
        port: 5001
        data_alerts_path: alerts
        data_host_path: labels.instance
        data_path_separator: .

  rules:
    - name: condicao DEBUG
      condition: event.payload is defined
      action:
        debug:
          var: event.payload

    - name: Adiciona user do grupo de VPN
      condition: >
        (event.payload.vpn is defined) and
        (event.payload.vpn.tipo == "request_access")
      action:
        run_job_template:
          name: "VPN - Add user AD to VPN"
          organization: devops
          job_args:
            extra_vars:
              vpn_automations: "{{ event.payload.vpn }}"
            instance_groups: [2]
